version: '3.8'

services:
  # Flask 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    volumes:
      - backend_uploads:/app/uploads
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT}
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  # Next.js 前端服务  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_PUBLIC_API_URL=http://backend:5000
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

# 数据卷（持久化存储用户上传的文件）
volumes:
  backend_uploads:
    driver: local

# 网络配置
networks:
  app-network:
    driver: bridge
